-- Notification restructure: unstructured display strings -> structured atomic
-- fields with robust, atomic deduplication.
--
-- Before: (id, userId, type, actorId?, chatId?, postId?, body?, readAt?, createdAt)
--   * `body` held a pre-rendered sentence (actor name baked in -> double-render).
--   * No unique constraint -> the same event could create duplicate rows.
--
-- After: (id, recipientId, actorId, type, targetId, metadata, readAt,
--         createdAt, updatedAt)
--   * targetId unifies chatId/postId/requester into one deep-link pointer.
--   * metadata (jsonb) carries raw render context ({ preview, roomName,
--     chatType }); the actor's name/avatar are joined live from `user`.
--   * A UNIQUE index on (recipientId, actorId, type, targetId) makes
--     ON CONFLICT DO UPDATE truly atomic -> one row per logical notification.
--
-- Notifications are ephemeral (regenerated by live events) and nothing
-- foreign-keys into this table, so we drop and recreate rather than run a
-- lossy column-by-column backfill. Applied directly against the database to
-- match this project's drizzle `push` workflow (no migration journal).

DROP TABLE IF EXISTS "notification" CASCADE;

CREATE TABLE "notification" (
  "id" text PRIMARY KEY NOT NULL,
  "recipientId" text NOT NULL,
  "actorId" text NOT NULL,
  "type" text NOT NULL,
  "targetId" text NOT NULL,
  "metadata" jsonb,
  "readAt" timestamp,
  "createdAt" timestamp DEFAULT now() NOT NULL,
  "updatedAt" timestamp DEFAULT now() NOT NULL
);

CREATE UNIQUE INDEX "notification_dedupe_unique"
  ON "notification" ("recipientId", "actorId", "type", "targetId");
CREATE INDEX "notification_recipient_created_idx"
  ON "notification" ("recipientId", "createdAt");
CREATE INDEX "notification_recipient_read_idx"
  ON "notification" ("recipientId", "readAt");
